### ISSUE TITLE
Differentiate from pytest-cache

### ISSUE THREAD

**Issue by pjz** [dmerejkowsky/pytest-runfailed#6]
How is this different from pytest-cache's `pytest -lf` option?

**Comment by dmerejkowsky** [comment]
It's not. I just did not know about pytest-cache when I wrote this

**Comment by pjz** [comment]
Ah! Okay!

**Comment by dmerejkowsky** [comment]
Note that pytest-cache using excecnet, whereas pytest-runfailed only uses pickle, which means you can get trouble if you use pytest-runfailed and switch python versions between test runs
